name: Publish Package to NPM
on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          npm install
          npm install -g typescript  # Ensure TypeScript is available

      - name: Build
        run: |
          tsc
          npm run build

      - name: Publish to NPM
        run: npm publish --access public # Added --access public flag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
